### ISSUE TITLE
TerminatedWorkerError on "svc pre-hubert"

### ISSUE THREAD

**Issue by pierluigizagaria** [34j/so-vits-svc-fork#106]
```
Traceback (most recent call last):
  File "/home/ubuntu/so-vits-svc/venv/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/so_vits_svc_fork/__main__.py", line 523, in pre_hubert
    preprocess_hubert_f0(
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/so_vits_svc_fork/preprocess_hubert_f0.py", line 102, in preprocess_hubert_f0
    Parallel(n_jobs=n_jobs)(
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/so-vits-svc/venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```
I'm trying to train a model using WSL on windows with ROCm for AMD GPUs.
I'm getting this error when running the `svc pre-hubert` command.
How can I limit the RAM used?

**Comment by BlueAmulet** [comment]
You can reduce the number of workers by passing `-n #` to the command, personally I use `-n 2` otherwise I run out of memory

**Comment by pierluigizagaria** [comment]
Thank you! Unfortunately I discovered that ROCm does not work on WSL installations.

**Comment by 34j** [comment]
Would you mind trying [this version](https://github.com/34j/so-vits-svc-fork/tree/feat/openml)?

**Comment by pierluigizagaria** [comment]
Sure, how can I easily install it?

**Comment by 34j** [comment]
pip install -U git+https://github.com/34j/so-vits-svc-fork.git@feat/openml

**Comment by 34j** [comment]
Migrate to #120
