### ISSUE TITLE
Invalid Start Byte error

### ISSUE THREAD

**Issue by Enframed** [34j/so-vits-svc-fork#117]
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Star Guard 719\Documents\sovits\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\Star Guard 719\Documents\sovits\venv\lib\site-packages\so_vits_svc_fork\train.py", line 77, in run
    train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps)
  File "C:\Users\Star Guard 719\Documents\sovits\venv\lib\site-packages\so_vits_svc_fork\data_utils.py", line 26, in __init__
    self.audiopaths = load_filepaths_and_text(audiopaths)
  File "C:\Users\Star Guard 719\Documents\sovits\venv\lib\site-packages\so_vits_svc_fork\utils.py", line 551, in load_filepaths_and_text
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "C:\Users\Star Guard 719\Documents\sovits\venv\lib\site-packages\so_vits_svc_fork\utils.py", line 551, in <listcomp>
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 370: invalid start byte
```
Getting this error when running svc train, went through all other steps without issue. Reinstalled Python and tried on both 3.8 and 3.10

**Comment by 34j** [comment]
I believe it is a character code issue.

**Comment by 34j** [comment]
This was a torch.save,load issue. Fix with a temporary solution.

**Comment by 34j** [comment]
@allcontirbutors add Enframed bug
