### ISSUE TITLE
error in training on colab

### ISSUE THREAD

**Issue by ruckusmattster** [34j/so-vits-svc-fork#133]
The tensorboard extension is already loaded. To reload it, use:
```
  %reload_ext tensorboard
Reusing TensorBoard on port 6006 (pid 4018), started 0:07:57 ago. (Use '!kill 4018' to kill it.)
[09:58:13] Version: 1.4.1
[09:58:16] Version: 1.4.1
[09:58:18] {'train': {'log_interval': 200, 'eval_interval': 800, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 10240, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/44k/train.txt', 'validation_files': 'filelists/44k/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 200}, 'spk': {'matt': 0}, 'model_dir': 'drive/MyDrive/so-vits-svc-fork/logs/44k'}
2023-03-26 09:58:18.101134: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-26 09:58:19.110665: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-26 09:58:19.110804: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-26 09:58:19.110825: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[09:58:19] NumExpr defaulting to 2 threads.
[09:58:20] Added key: store_based_barrier_key:1 to store for rank: 0
[09:58:20] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
[09:58:24] 'emb_g.weight'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/utils.py", line 413, in load_checkpoint
    new_state_dict[k] = saved_state_dict[k]
KeyError: 'emb_g.weight'
[09:58:24] emb_g.weight is not in the checkpoint
[09:58:24] Loaded checkpoint 'drive/MyDrive/so-vits-svc-fork/logs/44k/G_0.pth' (iteration 0)
[09:58:24] Loaded checkpoint 'drive/MyDrive/so-vits-svc-fork/logs/44k/D_0.pth' (iteration 0)
[09:58:24] Start training
  0% 0/10000 [00:00<?, ?it/s][09:58:27] Version: 1.4.1
[09:58:27] Version: 1.4.1
[09:58:35] Reducer buckets have been rebuilt in this iteration.
[09:58:36] /usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

[09:58:37] Train Epoch: 1 [0%]
[09:58:37] Losses: [2.5402114391326904, 2.7362656593322754, 9.689486503601074, 52.52246856689453, 7.239556312561035], step: 0, lr: 0.0001
[09:58:37] Saving checkpoints...
[09:58:38] Version: 1.4.1
[09:58:42] Saving model and optimizer state at iteration 1 to drive/MyDrive/so-vits-svc-fork/logs/44k/G_0.pth
[09:58:44] Saving model and optimizer state at iteration 1 to drive/MyDrive/so-vits-svc-fork/logs/44k/D_0.pth
[09:58:47] Cleaning old checkpoints...
[09:58:47] Reducer buckets have been rebuilt in this iteration.
  0% 0/10000 [00:28<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 128, in train
    train(config_path=config_path, model_path=model_path)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 49, in train
    mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 158, in run
    train_and_evaluate(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 200, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
EOFError: Caught EOFError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/data_utils.py", line 102, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/data_utils.py", line 51, in get_audio
    spec = torch.load(spec_filename)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by 34j** [comment]
This is an error that occurs when the checkpoint is an incomplete file for some reason.

**Comment by ruckusmattster** [comment]
> checkpoint is an incomplete file for some reason.
i reckon that might be my fault- i messed up a couple steps. so just restarting the notebook and running it again should solve it? also can i ask- do you run EVERY cell in order or are some cells optional? (cluster train vs train)

**Comment by 34j** [comment]
Just delete the corrupt file and resume training.(svc train only) I believe this is due to insufficient drive space or interruption while writing the checkpoint.

**Comment by ruckusmattster** [comment]
![image](https://user-images.githubusercontent.com/77196088/227775901-b9cce167-d9dd-4c0e-9ed2-03afa743e891.png)
how do i fix this error?

**Comment by ruckusmattster** [comment]
automatic preprocessing throws this error, is the local training any easier? i tried once but couldnt get it working but id be willing to give it another go

[12:40:53] Version: 1.4.2
Preprocessing:  71% 75/106 [01:18<01:29,  2.88s/it][12:42:14] exception calling callback for <Future at 0x7fa7aeaef760 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/dist-packages/tqdm_joblib/__init__.py", line 20, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 360, in __call__
    self.parallel.dispatch_next()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 797, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/reusable_executor.py", line 177, in submit
    return super(_ReusablePoolExecutor, self).submit(
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
Preprocessing:  74% 78/106 [01:18<00:28,  1.01s/it]
Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 420, in pre_resample
    preprocess_resample(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocess_resample.py", line 111, in preprocess_resample
    Parallel(n_jobs=n_jobs)(
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/dist-packages/tqdm_joblib/__init__.py", line 20, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 360, in __call__
    self.parallel.dispatch_next()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 797, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/reusable_executor.py", line 177, in submit
    return super(_ReusablePoolExecutor, self).submit(
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}

**Comment by MashiroSA** [comment]
@ruckusmattster 

According to the log, when the program performed the preprocessing step and reached the 75/106 data, the parallel processing worker of `joblib` that was invoked was abnormally terminated. As the log indicates, it may have exceeded the memory limit or may have been due to some deeper level errors.

I can't give you more helpful information. But I suggest you checking memory usage chart and your dataset first, try reducing the number of datasets and give it another try to test if it is a program issue. Most importantly, don't be discouraged. 😊

**Comment by 34j** [comment]
This is a memory error due to a recent change, there should be a new release in about 5 minutes, please restart your notebook and try again when it is released.

**Comment by ruckusmattster** [comment]
sorry to keep chucking errors at you but ive got

svc pre-hubert:
File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocess_hubert_f0.py", line 67, in _process_batch
    _process_one(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocess_hubert_f0.py", line 38, in _process_one
    c = utils.get_hubert_content(hubert_model, wav_16k_tensor=wav16k)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/utils.py", line 369, in get_hubert_content
    logits = hmodel.extract_features(**inputs)
  File "/usr/local/lib/python3.9/dist-packages/fairseq/models/hubert/hubert.py", line 535, in extract_features
    res = self.forward(
  File "/usr/local/lib/python3.9/dist-packages/fairseq/models/hubert/hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "/usr/local/lib/python3.9/dist-packages/fairseq/models/hubert/hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/fairseq/models/wav2vec/wav2vec2.py", line 895, in forward
    x = conv(x)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 519, in pre_hubert
    preprocess_hubert_f0(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocess_hubert_f0.py", line 96, in preprocess_hubert_f0
    Parallel(n_jobs=n_jobs)(
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '


train
File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 96, in train
    train(config_path=config_path, model_path=model_path)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 49, in train
    mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 158, in run
    train_and_evaluate(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 200, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/data_utils.py", line 102, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/data_utils.py", line 67, in get_audio
    f0 = np.load(filename + ".f0.npy")
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/44k/matty/sample_050.wav.f0.npy'

**Comment by Lordmau5** [comment]
Can you try modifying the colab so it runs `svc pre-resample -n 1` instead of just `svc pre-resample` and then try the rest again?

I had a similar issue locally, maybe that can also fix it for you

**Comment by ruckusmattster** [comment]
same error as before- is the colab working okay for you?

**Comment by Lordmau5** [comment]
> same error as before- is the colab working okay for you?

I haven't touched the colab anymore ever since I set it up locally to run on my own GPU I'm afraid :(

**Comment by MashiroSA** [comment]
Ok for me using v1.4.1. You can temporarily using this version by changing step `Install dependencies` by adding `==1.4.0` to specify the version as following and give it another try.
```
if BRANCH == "none":
    %pip install -U so-vits-svc-fork==1.4.0
```
🤔

**Comment by 34j** [comment]
> Can you try modifying the colab so it runs `svc pre-resample -n 1` instead of just `svc pre-resample` and then try the rest again?
> 
> I had a similar issue locally, maybe that can also fix it for you

It's a pre-hubert error, different issue. 
Are there any audio files being unusually short in `dataset/44k`?

**Comment by ruckusmattster** [comment]
ooh actually, looking now theres a couple. ill edit them out. otherwise ill try fumble through running it locally; its all set up but the file structure etc confuse me

**Comment by 34j** [comment]
![image](https://user-images.githubusercontent.com/55338215/227783536-eef86641-1c1b-49c0-ac2e-58d67a88bb05.png)
we need this in `pre-hubert`

**Comment by 34j** [comment]
I'm tired of it. It's a simple task and I'll ask someone else to do it. In addition, I am looking for a collaborator.

**Comment by ruckusmattster** [comment]
just a last ask- a screen recording of the install and train process would be godly- no need to any talking just show the steps in order no cuts or edits 🙏

**Comment by MashiroSA** [comment]
> just a last ask- a screen recording of the install and train process would be godly- no need to any talking just show the steps in order no cuts or edits 🙏
> 
> feel free to just say no if its a lot of work

>ooh actually, looking now theres a couple. ill edit them out. otherwise ill try fumble through running it locally; its all set up but the file structure etc confuse me

Sry 4 i cant give your a record now, but i can show u about my file structure.

![image](https://user-images.githubusercontent.com/40637516/227784703-668a4482-d7a6-4b74-bc05-67fd1fb19148.png)

Hopefully it can help you.

**Comment by ruckusmattster** [comment]
alright- everything looks right to me- local may just be the way to go- if i can figure that out  😆

**Comment by ruckusmattster** [comment]
![image](https://user-images.githubusercontent.com/77196088/227787159-b1dca2f4-f732-497e-aba2-cad36b1d6ba7.png)
where do i find this in the local install

**Comment by ruckusmattster** [comment]
![image](https://user-images.githubusercontent.com/77196088/227789024-9955bff9-2da3-4944-9c16-95c3e0ba02ff.png)
is this the correct location? do i create that folder? just drop a thumbs up if yes

**Comment by 34j** [comment]
> ![image](https://user-images.githubusercontent.com/77196088/227789024-9955bff9-2da3-4944-9c16-95c3e0ba02ff.png) is this the correct location? do i create that folder? just drop a thumbs up if yes

sovits/
If you have other questions, please ask them in Discussion.

**Comment by 34j** [comment]
@allcontributors add ruckusmattster bug
