### ISSUE TITLE
sizes number mismatch

### ISSUE THREAD

**Issue by blackrubystudiodev** [34j/so-vits-svc-fork#139]
**Describe the bug**
Training fails at step 0
```
Error:
`           INFO     [17:01:47] Start training                                                               train.py:154
  0%|                                                                                        | 0/10000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "d:\sw\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\sw\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\sw\miniconda3\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "d:\sw\miniconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\sw\miniconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\sw\miniconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\sw\miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\sw\miniconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\sw\miniconda3\lib\site-packages\so_vits_svc_fork\__main__.py", line 96, in train
    train(config_path=config_path, model_path=model_path)
  File "d:\sw\miniconda3\lib\site-packages\so_vits_svc_fork\train.py", line 49, in train
    mp.spawn(
  File "d:\sw\miniconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "d:\sw\miniconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "d:\sw\miniconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "d:\sw\miniconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "d:\sw\miniconda3\lib\site-packages\so_vits_svc_fork\train.py", line 158, in run
    train_and_evaluate(
  File "d:\sw\miniconda3\lib\site-packages\so_vits_svc_fork\train.py", line 200, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "d:\sw\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "d:\sw\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "d:\sw\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "d:\sw\miniconda3\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "d:\sw\miniconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "d:\sw\miniconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "d:\sw\miniconda3\lib\site-packages\so_vits_svc_fork\data_utils.py", line 145, in __call__
    spec_padded[i, :, : spec.size(1)] = spec
RuntimeError: expand(torch.FloatTensor{[2, 790, 844]}, size=[2, 790]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)`
```
**To Reproduce**

`svc train`

**Additional context**
all previous steps ran smoothly

**Comment by heyfixit** [comment]
same here, recently updated to `1.4.3`

**Comment by 34j** [comment]
svc pre-hubert -f should fix

Sorry for your inconvenience

**Comment by heyfixit** [comment]
seems good in `2.1.0`

I wiped down to just raw dataset and went from there again.
