### ISSUE TITLE
GUI doesn't load

### ISSUE THREAD

**Issue by xdanielc** [34j/so-vits-svc-fork#144]
**Describe the bug**
I type svcg in the terminal and something seems to pop up in the notification bar, but no ui loads and the console seems to be on the execution loop, waiting to log something else

**Additional context**
Build fairseq with Windows 10 SDK (10.0.20348.0)
Windows 10 64 bits
Nvidia GTX 1650
i7 9700K
RAM 16 Gb

**Comment by 34j** [comment]
Are you using wsl? Would you mind trying something else?

**Comment by xdanielc** [comment]
I'm using plain windows, why would I complicate things adding bloat to my ssd with the whole WSL (no hate towards linux) when I already had to install the visual studio C++ 14 build tools.
Also from the looks of the GUI, it seemed to be made with tkinter, not gtk even thought both are cross-platform.

**Comment by 34j** [comment]
Unknown bug. Please post the console output.

**Comment by xdanielc** [comment]
Ok, I found the error, apparently opening the console as administrator worked.

The error was this one:

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python310\\lib\\site-packages\\librosa\\util\\__pycache__\\tmpebfk671g'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 14, in <module>
    from .utils import ensure_hubert_model
  File "C:\Program Files\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line 13, in <module>
    import torchcrepe
  File "C:\Program Files\Python310\lib\site-packages\torchcrepe\__init__.py", line 1, in <module>
    from . import decode
  File "C:\Program Files\Python310\lib\site-packages\torchcrepe\decode.py", line 1, in <module>
    import librosa
  File "C:\Program Files\Python310\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Program Files\Python310\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Program Files\Python310\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Program Files\Python310\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Program Files\Python310\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Program Files\Python310\lib\site-packages\librosa\util\utils.py", line 1879, in <module>
    def __shear_dense(X, *, factor=+1, axis=-1):
  File "C:\Program Files\Python310\lib\site-packages\numba\core\decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "C:\Program Files\Python310\lib\site-packages\numba\core\dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "C:\Program Files\Python310\lib\site-packages\numba\core\caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "C:\Program Files\Python310\lib\site-packages\numba\core\caching.py", line 333, in __init__
    locator = cls.from_function(py_func, source_path)
  File "C:\Program Files\Python310\lib\site-packages\numba\core\caching.py", line 180, in from_function
    self.ensure_cache_path()
  File "C:\Program Files\Python310\lib\site-packages\numba\core\caching.py", line 107, in ensure_cache_path
    tempfile.TemporaryFile(dir=path).close()
  File "C:\Program Files\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Program Files\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python310\lib\tempfile.py", line 263, in _mkstemp_inner
    _os.access(dir, _os.W_OK)):
KeyboardInterrupt
```

**Comment by 34j** [comment]
Please use a virtual environment.
