### ISSUE TITLE
`svc pre-split` command not functional

### ISSUE THREAD

**Issue by ThrowawayAccount01** [34j/so-vits-svc-fork#150]
Found some bugs. After the preprocessing commits from 2.0.0 and up, the command `svc pre-resample -h` will no longer work.

```
(venv) C:\Users\LXC PC\Desktop\sovits\venv\Scripts>svc pre-resample -h
[14:39:02] INFO     [14:39:02] Version: 2.1.0                                                             __main__.py:20
Error: Option '-h' requires an argument.
```

In addition, the command `svc pre-split` does not work as well.

```
(venv) C:\Users\LXC PC\Desktop\sovits\venv\Scripts>svc pre-split -h
[14:55:42] INFO     [14:55:42] Version: 2.1.0                                                             __main__.py:20
Error: Option '-h' requires an argument.
```

```
(venv) C:\Users\LXC PC\Desktop\sovits\venv\Scripts>svc pre-split -i "C:\Users\LXC PC\Desktop\sovits\venv\Scripts\dataset_raw\hapiraw"
[14:56:17] INFO     [14:56:17] Version: 2.1.0                                                             __main__.py:20
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\LXC PC\Desktop\sovits\venv\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\__main__.py", line 668, in pre_split
    from .preprocess_split import preprocess_split
  File "C:\Users\LXC PC\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\preprocess_split.py", line 45, in <module>
    input_dir: Path | str,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by 34j** [comment]
-h should be -ho or -hop
Need to add from __futures
