### ISSUE TITLE
Error when trying to infer

### ISSUE THREAD

**Issue by xdanielc** [34j/so-vits-svc-fork#172]
I'm using one of the pretrained models from huggin face and I get a permission error, even thought I'm running the GUI from an administrator console

```
C:\Users\Daniel\Desktop\pre
[23:04:53] INFO     [23:04:53] Event infer, values {'model_path': 'C:/Users/Daniel/Desktop/pre/D_0.pth',      gui.py:507                    'model_path_browse': 'C:/Users/Daniel/Desktop/pre/D_0.pth', 'config_path': '',
                    'config_path_browse': '', 'cluster_model_path': '', 'cluster_model_path_browse': '',
                    'speaker': '', 'silence_threshold': -35.0, 'transpose': 12.0, 'auto_predict_f0': False,
                    'f0_method': 'dio', 'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1,
                    'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path':
                    'C:/Users/Daniel/Desktop/flowers.wav', 'input_path_browse':
                    'C:/Users/Daniel/Desktop/flowers.wav', 'auto_play': True, 'crossfade_seconds': 0.05,
                    'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microsoft Sound Mapper - Input (MME)', 'output_device': 'Altavoces
                    (Realtek(R) Audio) (Windows DirectSound)', 'passthrough_original': False, 'presets':
                    'Default VC (GPU, GTX 1060)', 'preset_name': '', 'use_gpu': True}
[23:04:54] ERROR    [23:04:54] [Errno 13] Permission denied: '.'                                              gui.py:584                    Traceback (most recent call last):
                      File "C:\Program Files\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 550,
                    in main
                        infer(
                      File "C:\Program Files\Python310\lib\site-packages\so_vits_svc_fork\inference_main.py",
                    line 45, in infer
                        svc_model = Svc(
                      File "C:\Program
                    Files\Python310\lib\site-packages\so_vits_svc_fork\inference\infer_tool.py", line 104, in
                    __init__
                        self.hps_ms = utils.get_hparams_from_file(config_path)
                      File "C:\Program Files\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line
                    574, in get_hparams_from_file
                        config = json.loads(Path(config_path).read_text())
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'
```

**Comment by 34j** [comment]
That's because you don't enter config path
