### ISSUE TITLE
Inference Bug after upgrading from 0.3.0

### ISSUE THREAD

**Issue by rcr0148** [34j/so-vits-svc-fork#21]
Hi! The GUI was working perfectly until I upgraded from 0.3.0 to 0.6.2. Now anytime I try to start an inference, it errors out and closes the interface. Here is the error I get:

`(colab0) C:\Users\Haven>svcg
[12:51:04] INFO     [12:51:04] Event infer, values {'model_path':                                             gui.py:285
                    'C:/Users/Haven/Desktop/UI_for_So-Vits-SVC-main/folderDumpText/offlinesovit/so-vits-svc
                    /logs/44k/G_192500.pth', 'model_path_browse':
                    'C:/Users/Haven/Desktop/UI_for_So-Vits-SVC-main/folderDumpText/offlinesovit/so-vits-svc
                    /logs/44k/G_192500.pth', 'config_path':
                    'C:/Users/Haven/Desktop/UI_for_So-Vits-SVC-main/folderDumpText/offlinesovit/so-vits-svc
                    /configs/config.json', 'config_path_browse':
                    'C:/Users/Haven/Desktop/UI_for_So-Vits-SVC-main/folderDumpText/offlinesovit/so-vits-svc
                    /configs/config.json', 'cluster_model_path': '', 'cluster_model_path_browse': '',
                    'speaker': 'sp', 'silence_threshold': -30.0, 'transpose': 0.0, 'auto_predict_f0': True,
                    'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5,
                    'absolute_thresh': False, 'input_path': 'C:/Users/Haven/Desktop/aii.wav', 'Browse':
                    'C:/Users/Haven/Desktop/aii.wav', 'auto_play': True, 'crossfade_seconds': 0.1,
                    'block_seconds': 1.0, 'realtime_algorithm': '2 (Divide by speech)', 'input_device':
                    'Microsoft Sound Mapper - Input', 'output_device': 'Microsoft Sound Mapper - Output',
                    'use_gpu': True}
Traceback (most recent call last):
  File "C:\Users\Haven\anaconda3\envs\colab0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Haven\anaconda3\envs\colab0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Haven\anaconda3\envs\colab0\Scripts\svcg.exe\__main__.py", line 7, in <module>
  File "C:\Users\Haven\anaconda3\envs\colab0\lib\site-packages\so_vits_svc_fork\gui.py", line 301, in main
    from .inference_main import infer
  File "C:\Users\Haven\anaconda3\envs\colab0\lib\site-packages\so_vits_svc_fork\inference_main.py", line 12, in <module>
    from .inference.infer_tool import RealtimeVC, RealtimeVC2, Svc
ImportError: cannot import name 'RealtimeVC' from 'so_vits_svc_fork.inference.infer_tool' (C:\Users\Haven\anaconda3\envs\colab0\lib\site-packages\so_vits_svc_fork\inference\infer_tool.py)
`

I've confirmed by pip uninstall and forcing the 0.3.0 version that the older version still works for me though!

**Comment by 34j** [comment]
Thank you for using it. It is strange because if you look at infer_tool.py in the repository, the two classes are present in the USUSE. 

Please answer the following in order

- Are you using anaconda?
- Please paste the infer_tool.py in your site_packages.
- Please try again in a venv environment and report your results
