### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

### ISSUE THREAD

**Issue by 906051999** [34j/so-vits-svc-fork#215]
```
(venv) (base) PS path> svcg
Traceback (most recent call last):
  File "pypath\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "pypath\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "path\venv\Scripts\svcg.exe\__main__.py", line 7, in <module>
  File "path\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 510, in main
    update_devices()
  File "path\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 468, in update_devices
    ) = get_devices()
  File "path\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 64, in get_devices
    devices = sd.query_devices()
  File "path\venv\lib\site-packages\sounddevice.py", line 564, in query_devices
    return DeviceList(query_devices(i)
  File "path\venv\lib\site-packages\sounddevice.py", line 564, in <genexpr>
    return DeviceList(query_devices(i)
  File "path\venv\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
```
- Perhaps it was due to the presence of Chinese
- Can't Chinese appear anywhere in this project?
- Maybe you can tell me that those paths cannot contain

**Comment by 34j** [comment]
This seems to be `sounddevice` issue...

**Comment by lededev** [comment]
I got the same error. The if on windows branch is not cover all the conditions, remove if and will resovle, It will exit when double except if failed, no need add if block.
```python
    try:
        # We don't know beforehand if DirectSound and MME device names use
        # 'utf-8' or 'mbcs' encoding.  Let's try 'utf-8' first, because it more
        # likely raises an exception on 'mbcs' data than vice versa, see also
        # https://github.com/spatialaudio/python-sounddevice/issues/72.
        # All other host APIs use 'utf-8' anyway.
        name = name_bytes.decode('utf-8')
    except UnicodeDecodeError:
        if info.hostApi in (
                _lib.Pa_HostApiTypeIdToHostApiIndex(_lib.paDirectSound),
                _lib.Pa_HostApiTypeIdToHostApiIndex(_lib.paMME)):
            name = name_bytes.decode('mbcs')
        else:
            raise
```
change to
```python
    try:
        # We don't know beforehand if DirectSound and MME device names use
        # 'utf-8' or 'mbcs' encoding.  Let's try 'utf-8' first, because it more
        # likely raises an exception on 'mbcs' data than vice versa, see also
        # https://github.com/spatialaudio/python-sounddevice/issues/72.
        # All other host APIs use 'utf-8' anyway.
        name = name_bytes.decode('utf-8')
    except UnicodeDecodeError:
        name = name_bytes.decode('mbcs')
```
