### ISSUE TITLE
CUDA Out of Memory during training

### ISSUE THREAD

**Issue by Enframed** [34j/so-vits-svc-fork#219]
Hi, I've trained a few models without issue but after updating to 3.0 when trying to train a new model I run out of memory. I'm using the same dataset as before and there's no issues until the SVC Train command. Any idea what might be causing it? I can't make head or tail of the error message.

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\__main__.py", line 128, in train
    train(
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\train.py", line 53, in train
    mp.spawn(
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\train.py", line 167, in _run
    _train_and_evaluate(
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\train.py", line 266, in _train_and_evaluate
    y_d_hat_r, y_d_hat_g, _, _ = net_d(y, y_hat.detach())
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\modules\descriminators.py", line 137, in forward
    y_d_r, fmap_r = d(y)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\so_vits_svc_fork\modules\descriminators.py", line 81, in forward
    x = F.leaky_relu(x, modules.LRELU_SLOPE)
  File "C:\Users\Star Guard 719\Documents\sovits new\venv\lib\site-packages\torch\nn\functional.py", line 1632, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 10.00 GiB total capacity; 9.13 GiB already allocated; 0 bytes free; 9.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by 34j** [comment]
Simply reduce batch_size

**Comment by Meldoner** [comment]
I have the same problem
