### ISSUE TITLE
Trouble with training on google colab

### ISSUE THREAD

**Issue by Meldoner** [34j/so-vits-svc-fork#220]
**Describe the bug**
I have a model trained for only 5600 steps, then the colab turned me off because of the limits, when I want to continue training I get this error at the stage Copy configs file:
  0% 0/15 [00:00<?, ?it/s]
  0% 0/15 [00:00<?, ?it/s]
  0% 0/15 [00:00<?, ?it/s]
  0% 0/15 [00:00<?, ?it/s]
  0% 0/15 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 590, in pre_hubert
    preprocess_hubert_f0(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py", line 112, in preprocess_hubert_f0
    Parallel(n_jobs=n_jobs)(
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 10 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**To Reproduce**

**Additional context**
Is there anything you can do to help me? And how to continue training, I don't really understand

**Comment by 34j** [comment]
-n 2

**Comment by Meldoner** [comment]
> please add -n 2
where?

**Comment by Meldoner** [comment]
> please add -n 2

And you know what I have to do to continue training model that I do not need to run?

**Comment by Meldoner** [comment]
>nothing special is required for resuming

So I just have to execute all the code again one by one?

**Comment by 34j** [comment]
This is a bug. I'm going to bed now, so please use version 2 or earlier, or add -t so-vits-svc-4.0-v1-legacy to pre-config,

**Comment by Meldoner** [comment]
oh okay, thanks anyway

**Comment by kin0303** [comment]
> > please add -n 2
> 
> where?

I also have the same problem, -and 2 is put like below
```
F0_METHOD = "dio" #param ["crepe", "crepe-tiny", "parselmouth", "dio", "harvest"]
!svc pre-hubert -fm {F0_METHOD} -n 2
```

**Comment by Meldoner** [comment]
> You can run `!svc pre-hubert -h` to know what parameters you can use
I get it, only I have another problem, I wrote about it above

**Comment by Meldoner** [comment]
@34j  do you know how to fix the bug?

**Comment by 34j** [comment]
😴

**Comment by Meldoner** [comment]
> 😴

please help me when you come back

**Comment by kin0303** [comment]
> > You can run `!svc pre-hubert -h` to know what parameters you can use
> 
> I get it, only I have another problem, I wrote about it above

Have you tried this:
```!svc pre-hubert -fm {F0_METHOD} -n 2```
I also had the same problem, but it worked after adding ```-n 2```

**Comment by 34j** [comment]
@allcontributors add Meldoner bug
