### ISSUE TITLE
Colab - Can't resume Training after 60000 ?

### ISSUE THREAD

**Issue by AlonDan** [34j/so-vits-svc-fork#231]
Hello, thank you for sharing this wonderful fork!

I'm trying to resume training from G_60000.pth on Colab, 
I already resumed few days ago it was fine, and I want to keep training the model.

All the files are still on my Drive with the dataset (wav files) on the correct directory, the log directory with the config and everything that I just used when I did resume before.
Basically I didn't change anything but I still can't resume training for some reason.

On this step:
```
F0_METHOD = "crepe" #@param ["crepe", "crepe-tiny", "parselmouth", "dio", "harvest"]
!svc pre-hubert -fm {F0_METHOD}
```
I originally used "crepe" when I start trained it few days ago, so I made sure it was still selected.

Here are the errors from one step before I can press Train (trying to Train anyway gives more Fails because what I mentioned above didn't finish, usually it takes some time from what I remember to complete before I can start training:

```
[16:19:09] Version: 3.0.2
2023-04-04 16:19:11.918439: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-04 16:19:13.253368: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[16:19:14] NumExpr defaulting to 2 threads.
Downloading checkpoint_best_legacy_500.pt: 100% 1.24G/1.24G [00:05<00:00, 257MiB/s]
[16:19:22] n_jobs automatically set to 5, memory: 15098 MiB
2023-04-04 16:19:40.706272: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 16:19:40.768836: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 16:19:40.802156: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 16:19:40.808469: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 16:19:41.488811: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[16:19:55] current directory is /content
[16:19:55] HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[16:19:55] HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
[16:19:56] current directory is /content
[16:19:56] HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[16:19:56] current directory is /content
[16:19:56] HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[16:19:56] HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
[16:19:56] current directory is /content
[16:19:56] HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[16:19:56] HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
[16:19:56] HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
[16:19:56] current directory is /content
[16:19:56] HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[16:19:56] HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 590, in pre_hubert
    preprocess_hubert_f0(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py", line 139, in preprocess_hubert_f0
    Parallel(n_jobs=n_jobs)(
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**To Reproduce**
Unfortunately I have no idea how to reproduce this, all I did was to try resume training of the model as I already did few days ago while it was working fine. 
I don't understand why it's not allowing me to continue resume training since I'm not a programmer.

Is this a bug or the limit is just 60000 per model? 
config files settings I used are the default, I didn't manipulate it in anyway within the file.

I could resume few days ago, now with the same Colab copy I can't.
It's important to mention that I didn't change anything different for resuming.

Thanks ahead for any solution! 🙏

**Comment by Meldoner** [comment]
same problem

**Comment by AlonDan** [comment]
I just tried a FRESH clean training from scratch... new dataset
I get the same errors, it seems like it's not only for resuming.

**Comment by BlueAmulet** [comment]
The issue here is that it's creating too many jobs (`n_jobs automatically set to 5`), and running out of memory. The fix for this is to limit the number of jobs by adding `-n 2` to the pre-hubert command.

The thing with `so-vits-svc-4.0v1-legacy` is unrelated and is because Meldoner was resuming training of a legacy model.

**Comment by AlonDan** [comment]
Thanks for the reply @BlueAmulet 🙏

When using `svc pre-hubert -fm crepe -n 2` and it's still out of memory, or at least it show lots of errors and not finishing...

If I do it again and again, **does it RESUME ?** 🤔
I'm asking because it doesn't show that it went to 100% it start always from 0% and crashes around 20% - 30% with some tests I just did.
Maybe I need to do it many times because it's out of memory on Colab.

I'm trying a FRESH training from scratch, and even with the -n 2 it can't finish the job
I have about 12 minutes WAV files split into 5-10 seconds each. it wasn't a problem few days ago, I'm guessing that the Colab is updated and this causing all the new issues but I'm not sure.

**Comment by BlueAmulet** [comment]
pre-hubert shuffles the list of files it processes, so the problematic wav file may end up earlier or later in the list. If you're still running out of memory, then you can try doing `-n 1` instead.

When you run the command again by default it will reprocess all files again even if they've already been done before, to avoid that also add `-nf` or `--no-force-rebuild` to the command

It does kind of seem like if it's randomly crashing, you might just have a wav file in the dataset that is too long. Even if limiting the number of jobs worked you might run into training issues once it eventually uses that wav file again.

**Comment by AlonDan** [comment]
Thanks for the tips @BlueAmulet 🙏

My longest WAV is 9 second shortest one is 5 seconds.
I used the same dataset with the older Colab it was fine I got to 60000 but then this problem started.

I also tried n -1  but it couldn't get to 40-50 % this time (it feels random) I also tried another dataset (less WAV files, around 5-8 sec) that worked before but from scratch, I get the same errors no matter what.

I will try the `-nf` and the `--no-force-rebuild` as you suggested, I hope it will allow me to complete the crepe stage so I can start train in Colab.

I'm thinking that the Colab last update changed a lot, I can't really tell but I could train with it easily, now it's impossible to train any of my datasets.

Thanks again for trying to help, I will give your tips a try.

**Comment by Meldoner** [comment]
@BlueAmulet Would reducing batch_size help get rid of the memory problem?

**Comment by BlueAmulet** [comment]
The number of jobs used in pre-hubert is a similar concept to the batch_size when training. Regardless they are unable to finish the pre-hubert step and haven't gotten to training yet.

**Comment by AlonDan** [comment]
@BlueAmulet I just tried the `--no-force-rebuild` it crashed and crashed again every time in different percentage, but at the third time... it complete it so I guess it did the job in the "hard way" now I need to see if it will allow me to train.

**Comment by AlonDan** [comment]
Thanks for the fixes @34j ❤ now it seems to work like it was before.

After trying the new version you can set the default Batch to 16 (seems to fail on anything above) but it's better than 12.

before that I couldn't go above 12, also everything else works just FINE now, good job!👍

I found these DEFAULT **Config** for the Colab works GREAT:
So feel free to update it for everyone to have max, start
I change the learning rate from 0.0001 to 0.0002 it may or may not affect some other datasets, but I'm still exploring.

```
{
  "train": {
    "log_interval": **400**,
    "eval_interval": **800**,
    "seed": 1234,
    "epochs": 10000,
    "learning_rate": **0.0002**,
    "betas": [
      0.8,
      0.99
    ],
    "eps": 1e-09,
    "batch_size": **16**,
```

**Comment by 34j** [comment]
@allcontributors add AlonDan bug

**Comment by RubenStark** [comment]
So you just run your colab and it resumes automatically? 

Im on G_132.pth and I want to resume where I left but it starts on the G_0.pth
