### ISSUE TITLE
CUDA out of memory when training on colab from checkpoint

### ISSUE THREAD

**Issue by incoding0** [34j/so-vits-svc-fork#252]
**Describe the bug**
CUDA out of memory when running train section on colab
**To Reproduce**
Steps to reproduce the behavior:  training on colab 

**Additional context**
Add any other context about the problem here.  i had no issues few days ago
  
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 165, in _run
    _train_and_evaluate(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/train.py", line 241, in _train_and_evaluate
    y_d_hat_r, y_d_hat_g, _, _ = net_d(y, y_hat.detach())
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/modules/descriminators.py", line 137, in forward
    y_d_r, fmap_r = d(y)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/modules/descriminators.py", line 81, in forward
    x = F.leaky_relu(x, modules.LRELU_SLOPE)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 1632, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 14.75 GiB total capacity; 13.13 GiB already allocated; 2.81 MiB free; 13.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by 34j** [comment]
Please try batch size = 16

**Comment by incoding0** [comment]
> Please try batch size = 16
change which file?

**Comment by incoding0** [comment]
it worked thanks

**Comment by 34j** [comment]
@allcontributors add 75aosu bug
