### ISSUE TITLE
[Manjaro Linux x86_64] Library 'libportaudio.so.2'/`GLIBCXX_3.4.30' cannot be found

### ISSUE THREAD

**Issue by acfsas** [34j/so-vits-svc-fork#328]
I attempted to run svcg and I get this error message:
`Traceback (most recent call last):
  File "/home/person/anaconda3/bin/svcg", line 5, in <module>
    from so_vits_svc_fork.gui import main
  File "/home/person/anaconda3/lib/python3.10/site-packages/so_vits_svc_fork/gui.py", line 8, in <module>
    import sounddevice as sd
  File "/home/person/anaconda3/lib/python3.10/site-packages/sounddevice.py", line 72, in <module>
    _lib = _ffi.dlopen(_libname)
OSError: cannot load library 'libportaudio.so.2': /home/person/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libjack.so.0)
`

RUN DOWN OF MY ATTEMPT TO FOLLOW THIS TUTORIAL:

I installed 'Anaconda3-2023.03-Linux-x86_64.sh' through the terminal, which resulted in anaconda3 and it's contents being made in my home folder. But I tried to run it as a normal user and 'conda' wasn't a recognized command, so I had to add my 'conda' path to my .zsh file in bash. After that was completed I got another error when I tried to create a name for conda, which was resolved by inputting the command "conda init zsh". I then installed  
**Additional context**

**Comment by 34j** [comment]
Maybe importing sounddevice is very strugging for some people and should be surrounded by try-catch for all

**Comment by timawesomeness** [comment]
If anyone else runs into this issue, the solution is to upgrade libstdcxx-ng to version 12.x ([`conda install -c conda-forge libstdcxx-ng=12`](https://stackoverflow.com/a/74533050/6952238)).
