### ISSUE TITLE
"is not a directory" error even though the directory DOES exist

### ISSUE THREAD

**Issue by Cheerioshi** [34j/so-vits-svc-fork#357]
I went through the process step by step with the youtube tutorial. https://www.youtube.com/watch?v=tZn0lcGO5OQ
When I finally came to "svc train" stage, I get the following error:

tensorflow.python.framework.errors_impl.FailedPreconditionError: logs\44k\lightning_logs is not a directory

However, that exact directory does exist.
Similar thing happened when I tried to run the original so-vits-svc (pre fork version), giving me the following error message at the training stage also:
tensorflow.python.framework.errors_impl.FailedPreconditionError: logs\44k is not a directory

Please can someone help with this?

**Comment by Cheerioshi** [comment]
full error message:

Trainable params: 91.9 M
Non-trainable params: 0
Total params: 91.9 M
Total estimated model params size (MB): 367
Traceback (most recent call last):
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\lightning\fabric\loggers\tensorboard.py", line 202, in log_metrics
    self.experiment.add_scalar(k, v, step)
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\lightning\fabric\loggers\logger.py", line 114, in experiment
    return fn(self)
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\lightning\fabric\loggers\tensorboard.py", line 185, in experiment
    self._experiment = SummaryWriter(log_dir=self.log_dir, **self._kwargs)
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 247, in __init__
    self._get_file_writer()
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Users\yoshi\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: logs\44k\lightning_logs is not a directory

**Comment by Cheerioshi** [comment]
for anyone who is having the same trouble
the problem was I had all the files in the Onedrive folder, which is an online folder.
