### ISSUE TITLE
GUI error Mac m1

### ISSUE THREAD

**Issue by remycoopermusic** [34j/so-vits-svc-fork#386]
**Describe the bug**
Hi guys, I'm having issues opening the GUI. It opens for a second and closes immediately. Anyone who's how to fix it?

**To Reproduce**
Open terminal
cd *folder location* -> enter
svcg -> enter

**Additional context**
I think I installed everything correctly?  I did the following in the cd location of the folder:

python -m pip install -U pip setuptools wheel
pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -U so-vits-svc-fork
pip install -U so-vits-svc-fork

LOG:
(base) username@device so-vits-svc-fork % svcg
[14:40:47] INFO     [14:40:47] version: 3.10.0                        gui.py:100
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/bin/svcg", line 8, in <module>
    sys.exit(main())
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/gui.py", line 500, in main
    update_devices()
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/gui.py", line 458, in update_devices
    ) = get_devices()
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/gui.py", line 81, in get_devices
    input_devices_indices = [d["index"] for d in devices if d["max_input_channels"] > 0]
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/gui.py", line 81, in <listcomp>
    input_devices_indices = [d["index"] for d in devices if d["max_input_channels"] > 0]
KeyError: 'index'

(Used "username" instead of the actual name)

**Comment by remycoopermusic** [comment]
Running an anaconda container worked for me: https://www.youtube.com/watch?v=kdMpB2YCqqU
